name: Publish Package to npmjs
on:
  release:
    types: [published]

jobs:
  publish:
    uses: cto-af/workflows/.github/workflows/publish.yml@main
    permissions:
      contents: read
      id-token: write
